<a href="https://colab.research.google.com/github/2303A51096/B2_PFDS_1096/blob/main/Labprogram04.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [2]:
a2=np.array([[1,2,3],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [3]:
a3=np.zeros((3,3))
print(a3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
a4=np.ones((2,4))
print(a4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
range=np.arange(0,10,2)
print(range)

[0 2 4 6 8]


In [10]:
rd=np.random.rand(2,3)
print(rd)

[[0.39631435 0.55772589 0.39052284]
 [0.444552   0.55407899 0.47156717]]


In [14]:
a=np.array([[1,2,3],[4,5,6]])
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.size)
print(a.itemsize)

(2, 3)
2
int64
6
8


In [15]:
a=np.array([10,20,30,40,50,60,70,80])
print(a[0])
print(a[-1])
print(a[1:5])
print(a[1:7:2])
print(a[0:8:3])


10
80
[20 30 40 50]
[20 40 60]
[10 40 70]


In [19]:
a=np.array([[10,20,30],[40,50,60]])
print(a[1][1])
print(a[0:1])

50
[[10 20 30]]
